name: Coverage

on:
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/kafka-devcontainer
          push: never
          runCmd: |
            # Install additional test dependencies
            pip install pytest-cov pytest-kafka coverage-badge

            # Run tests with coverage
            python -m pytest --cov=kafka_protobuf tests/ --cov-report=xml --cov-report=term
            
            # Generate coverage badge
            coverage-badge -o coverage.svg -f

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Comment coverage in PR
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: false
          verbose: true

      - name: Save coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage.svg